### ISSUE TITLE
Mesh hidden inside a polygon

### ISSUE THREAD

**Issue by erenovic** [autonomousvision/gaussian-opacity-fields#90]
Hello Zehao, congratulations on great work! 

I keep getting a thin polygon layer outside of the actual mesh. Do you have any insights on why that might happen during mesh extraction? The depth map, the mesh under the thin polygon layer and the Gaussians seem to be fine.

Sample mesh:
![image](https://github.com/user-attachments/assets/88b26036-716a-489b-9179-85bfdc0b0270)
Depth maps:
![image](https://github.com/user-attachments/assets/d976b37c-328c-4da4-819f-d5659b813939)

**Comment by niujinshuchong** [comment]
Hi, I think the reason is that when we generate tetrahedral points, there are points outside the viewing frustum of the input cameras and the opacity of these points are initiated as 1, which do not change in the later opacity evaluation step. When we run the marching tetrahedral, it detect edges that connect points with opacity < 0.5 and > 0.5. Therefore, some strange faces will appear. Maybe you can add a filtering step here (https://github.com/autonomousvision/gaussian-opacity-fields/blob/main/scene/gaussian_model.py#L412) to remove points outside the viewing frustum of all the cameras.

**Comment by erenovic** [comment]
Thank you Zehao, worked like a charm!

**Comment by niujinshuchong** [comment]
@erenovic Great that it works for you. Do you mind submit a PR for the fix? Thanks.

**Comment by erenovic** [comment]
I submitted PR #91 . Hope it helps :) It still requires setting a near-far value manually, without near-far culling, the benefits are minimal in dense view setting. I was using einops for batch operations, I hope it doesn't hurt.
